### ISSUE TITLE
Race command requires CGO_ENABLED=1

### ISSUE THREAD

**Issue by hemisto** [gourses/demo#1]
Setup @ windows:
- Visual Code
- WSL Debian
  - Git
  - Make
  - Docker engine
  - Go

Problem:
Running make, build, lint and image from Visual Code terminal works but when running `make show-coverage` will get an output
```
$ make show-coverage
.tools/go/go1.20.3 test -race -covermode atomic -coverprofile=target/coverage/unit.out ./...
go: -race requires cgo; enable cgo by setting CGO_ENABLED=1
make: *** [Makefile:60: unit-test] Error 1
```

**Comment by heppu** [comment]
Thanks for reporting! Should be fixed now.
